In [1]:
import pandas as pd
from keras.models import Sequential, model_from_json
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder

Using TensorFlow backend.

In [2]:
df = pd.read_csv("raw_input.csv")
df

    Home   ML  Puck Line   PL  Line Mvmt  net_goals
0      0  129        1.5 -230         11         -5
1      1 -149       -1.5  195        -11         -7
2      0  160        1.5 -170         20         -4
3      1 -190       -1.5  145        -20          5
4      0  116        1.5 -265          4          3
5      1 -136       -1.5  220         -4         -2
6      0  104        1.5 -285       -234          6
7      1 -124       -1.5  235        234          2
8      0  155        1.5 -190         -5         -6
9      1 -175       -1.5  161          5        -11
10     0  190        1.5 -140        -20         -8
11     1 -230       -1.5  120         30          6
12     0 -145       -1.5  210          0          7
13     1  125        1.5 -250          0        -13

In [3]:
def load_model():
    # loading model
    model = model_from_json(open('PL_model_architecture.json').read())
    model.load_weights('PL_model_weights.h5')
    model.compile(loss='categorical_crossentropy', optimizer='adam')
    return model

In [4]:
# load
model = load_model()

# predictions
predictions = model.predict_classes(df, verbose=2)
print(predictions)

[1 0 1 0 1 0 1 0 1 0 1 0 0 1]